version: '3.3'

services:
  jenkins:
   image: admintuts/jenkins-lts-alpine-docker:latest
   container_name: jenkins
   hostname: jenkins
   restart: unless-stopped
   env_file:
    - jenkins.env
   build:
     context: .
   ports:
    - 8090:8080
    - 50010:50000
    - 2375:2376
   volumes:
    - ./jenkins_data:/var/jenkins_home
    - /var/run/docker.sock:/var/run/docker.sock:rw
   networks:
    - default

volumes:
  jenkins_data:
networks:
  default:
   driver: bridge
